# Generated by Django 4.2.5 on 2024-01-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTrack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('x', models.DecimalField(decimal_places=20, max_digits=30)),
                ('y', models.DecimalField(decimal_places=20, max_digits=30)),
                ('width', models.DecimalField(decimal_places=20, max_digits=30)),
                ('height', models.DecimalField(decimal_places=20, max_digits=30)),
                ('rotate', models.IntegerField()),
                ('scalex', models.IntegerField()),
                ('scaley', models.IntegerField()),
            ],
        ),
    ]
