# Generated by Django 4.2.5 on 2024-01-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetrack',
            name='url',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
