# Generated by Django 4.2.5 on 2024-01-15 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0003_alter_imagetrack_rotate_alter_imagetrack_scalex_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagetrack',
            old_name='scalex',
            new_name='scaleX',
        ),
        migrations.RenameField(
            model_name='imagetrack',
            old_name='scaley',
            new_name='scaleY',
        ),
    ]
